import type { DefaultSeoProps } from "next-seo";

const SEO: DefaultSeoProps = {
  canonical: "https://nextjs-boilerplate-jet.vercel.app",
  description: "Generated by create next app",
  titleTemplate: "%s | NextJS Boilerplate",
  twitter: {
    handle: "@SamuelQuinones1",
    site: "@SamuelQuinones1",
    cardType: "summary_large_image",
  },
  openGraph: {
    type: "website",
    url: "https://nextjs-boilerplate-jet.vercel.app/",
    site_name: "nextjs-boilerplate",
    images: [
      {
        url: "https://nextjs-boilerplate-jet.vercel.app/favicon.ico",
        alt: "Vercel logo",
      },
    ],
  },
  additionalLinkTags: [{ rel: "icon", href: "/favicon.ico" }],
  additionalMetaTags: [
    { name: "viewport", content: "width=device-width, initial-scale=1" },
  ],
};

export default SEO;
