import type { DefaultSeoProps } from "next-seo";

const SEO: DefaultSeoProps = {
  canonical: process.env.NEXT_PUBLIC_BASE_URL,
  description: "Generated by create next app",
  titleTemplate: "%s | NextJS Boilerplate",
  twitter: {
    handle: "@SamuelQuinones1",
    site: "@SamuelQuinones1",
    cardType: "summary_large_image",
  },
  openGraph: {
    type: "website",
    url: process.env.NEXT_PUBLIC_BASE_URL,
    siteName: "nextjs-boilerplate",
    images: [
      {
        url: `${process.env.NEXT_PUBLIC_BASE_URL}/favicon.ico`,
        alt: "Vercel logo",
      },
    ],
  },
  additionalLinkTags: [{ rel: "icon", href: "/favicon.ico" }],
  additionalMetaTags: [
    { name: "viewport", content: "width=device-width, initial-scale=1" },
  ],
};

export default SEO;
